// Array containing 100 love notes
const loveNotes = [
    "Amisha, you are the light of my life. 💫",
    "Meesho, your smile is my favorite. 😊",
    "I love you more with each passing day. ❤️",
    "Your voice is like music to my ears. 🎶",
    "With you, every day feels like a beautiful dream. 🌸",
    "You are the reason for my happiness. 💖",
    "I can't imagine my life without you, Meesho. 🌍",
    "You're my sunshine on a cloudy day. ☀️",
    "Each moment with you is a memory I cherish. 💕",
    "I fall for you more every day, Meesho. 🌟",
    "Being with you makes every day brighter. ✨",
    "Your laugh is my favorite sound in the world. 🎶",
    "You complete me in ways I never knew possible. 💓",
    "You are the best thing that has ever happened to me. 💕",
    "Every time I look at you, I fall in love all over again. 💖",
    "Your presence makes everything better. 💫",
    "You are my home and my adventure, all at once. 🏠🌍",
    "I feel lucky to call you mine, Meesho. 💑",
    "Your love gives me strength and courage. 💪",
    "You are the most important person in my world. 🌎",
    "Every moment with you feels like a fairytale. 🏰",
    "You light up my life like no one else can. 🌟",
    "I am grateful for every moment we share together. 💖",
    "Your love is the melody my heart dances to. 🎵",
    "You make my world beautiful. 🌸",
    "Your kindness and love inspire me every day. 🌻",
    "With you, I have found my forever. 💞",
    "You are my happiness, my joy, my everything. 💫",
    "I can’t imagine my life without you, Meesho. 💕",
    "You bring out the best in me. 💓",
    "I love you more than words can ever express. 💖",
    "You are my dream come true. 🌠",
    "Your love is the most precious gift I have. 🎁",
    "You make every moment worthwhile. 💖",
    "You are my heart’s greatest treasure. 💎",
    "I adore everything about you, Meesho. 💖",
    "With you, every day is a new adventure. 🌍",
    "Your smile is my favorite sight. 😊",
    "You are the one my heart chose. 💞",
    "You make my world so much better. 💖",
    "Your love is the greatest blessing in my life. 🌸",
    "You fill my life with joy and love. 💓",
    "I love you more and more every single day. 💖",
    "You are my sunshine and my starlight. ☀️🌟",
    "With you, I have found my happily ever after. 💑",
    "You are the reason behind my smile. 😊",
    "I am so grateful to have you by my side. 💓",
    "You are my soulmate, my one true love. 💞",
    "Your love is my guiding light. 💫",
    "I fall more in love with you every day. 🌟",
    "You are my heart’s deepest desire. 💓",
    "You bring warmth and light into my life. ☀️",
    "With you, life is so much more beautiful. 🌸",
    "Your love fills my heart with happiness. 💖",
    "You are my love, my life, my everything. 💫",
    "I cherish every moment we spend together. 💕",
    "You make my world a brighter place. 🌟",
    "I love you more than words could ever say. 💖",
    "With you, every day is a blessing. 💓",
    "You are my reason to smile. 😊",
    "You are my heart’s true love. 💞",
    "You are my love story, my happy ending. 💖",
    "Your love is the greatest gift I’ve ever received. 🎁",
    "You make everything feel right in the world. 🌍",
    "I love you to the moon and back. 🌕",
    "Your love is the most precious thing in my life. 💓",
    "You are my forever and always. 💞",
    "You are the reason I believe in love. 💖",
    "You are my heart’s greatest joy. 💓",
    "You make my life complete. 💑",
    "You are my dream come true, Meesho. 💫",
    "I love every little thing about you. 💖",
    "You are the one I’ve been waiting for all my life. 💓",
    "You are the love of my life, and my best friend. 💕",
    "You are my heart’s most beautiful treasure. 💖",
    "I am so lucky to have you in my life. 💓",
    "You are my one true love, my soulmate. 💞",
    "You are the best thing that ever happened to me. 💖",
    "With you, every day is a new beginning. 💫",
    "You are the reason my heart beats with joy. 💓",
    "You are the love of my life, and my reason for being. 💖",
    "You are my forever, my always, my everything. 💞",
    "You make every moment of my life better. 💖",
    "Your love is my greatest adventure. 🌍",
    "You are the reason I wake up with a smile every day. 😊",
    "With you, life is more beautiful than ever. 💓",
    "You are my heart’s greatest love. 💞",
    "You are my dream, my love, my life. 💖",
    "Your love is my anchor, my home, my heart. 💓",
    "With you, I have found everything I’ve ever wanted. 💫",
    "You are my world, my love, my forever. 🌍"
];

// Function to display 100 love notes
function displayLoveNotes() {
    const notesContainer = document.getElementById('notes-container');
    
    loveNotes.forEach((note, index) => {
        const noteElement = document.createElement('p');
        noteElement.innerText = `Note ${index + 1}: ${note}`;
        notesContainer.appendChild(noteElement);
    });
}

// Call the function when the page loads
displayLoveNotes();

